In [ ]:
from evaluation.evaluation import evaluate_answer
import pandas as pd
from pathlib import Path

In [4]:
parquet = Path().resolve() / "data" / "processed" / "dataset_splitting" / "test.parquet"
df = pd.read_parquet(parquet)

df

,question_id,prompt,solution_col,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct,level
0,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, 2^8 is 256. 4^x is (2^2)^x = 2^(2x). So ...","If $2^8=4^x$, what is the value of $x$? Let’s ...",100,53,0.906188,True,Level 5
1,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, 2^8 equals 4^x. Since 4 is 2 squared, re...","If $2^8=4^x$, what is the value of $x$? Let’s ...",357,80,0.906188,True,Level 5
2,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, I need to solve 2^8 = 4^x. Let me rewrit...","If $2^8=4^x$, what is the value of $x$? Let’s ...",615,164,0.906188,True,Level 5
3,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, so I need to solve 2^8 equals 4^x. Hmm, ...","If $2^8=4^x$, what is the value of $x$? Let’s ...",873,257,0.906188,True,Level 5
4,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, so I need to solve the equation 2^8 = 4^...","If $2^8=4^x$, what is the value of $x$? Let’s ...",1131,439,0.906188,True,Level 5
...,...,...,...,...,...,...,...,...,...,...
14995,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (a...",Let $b \geq 2$ be an integer. Call a positive ...,3968,2658,1.130943,False,aime
14996,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,4226,2607,1.130943,False,aime
14997,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,4484,3041,1.130943,False,aime
14998,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,4742,2568,1.130943,False,aime
14999,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,5000,2827,1.130943,False,aime

In [12]:
cols_with_none = df_all[df_all['solution_col'].isna()]
cols_with_none

Empty DataFrame
Columns: [id, dataset, prompt, solution_col, level]
Index: []

In [13]:
solutions = []
for i in range(len(df_all)):
    row = df_all.iloc[i]
    solution = extract_boxed(row['solution_col'])
    solutions.append(solution)

In [14]:
df_cleaned = df_all
df_cleaned['solution_col'] = solutions
df_cleaned

,id,dataset,prompt,solution_col,level
0,0,gsm8k,Janet’s ducks lay 16 eggs per day. She eats th...,18,None
1,1,gsm8k,A robe takes 2 bolts of blue fiber and half th...,3,None
2,2,gsm8k,Josh decides to try flipping a house. He buys...,70000,None
3,3,gsm8k,James decides to run 3 sprints 3 times a week....,540,None
4,4,gsm8k,"Every day, Wendi feeds each of her chickens th...",20,None
...,...,...,...,...,...
2028,2028,amc,You are playing a game. A $2 \times 1$ rectang...,4,None
2029,2029,amc,When the roots of the polynomial \n\[P(x) = (...,6,None
2030,2030,amc,For how many integers $n$ does the expression\...,901,None
2031,2031,amc,"How many nonempty subsets $B$ of ${0, 1, 2, 3,...",144,None
2032,2032,amc,What is the area of the region in the coordina...,8,None

In [16]:
from pathlib import Path
df_all["dataset"].unique()

df_all.to_parquet(Path().resolve().parent.parent / "processed" / "eval_L1_bert" / "gsm8k_olympiad_amc.parquet")