In [2]:
import pandas as pd
from pathlib import Path


def split_by_question_type(df):
    aime_mask = df["question_id"].str.contains("aime", case=False, na=False)
    #aime_mask = df["question_id"] >= 500
    return df[aime_mask], df[~aime_mask]


def compute_metrics(df):
    mean_tokens = df["generated_think_tokens"].mean()
    percent_correct = df["is_correct"].mean() * 100
    return mean_tokens, percent_correct

In [50]:
df = pd.read_parquet(Path().resolve() / "regressor_results_aime_correct.parquet")
aime_df, math_df = split_by_question_type(df)

aime_mean_tokens, aime_percent_correct = compute_metrics(aime_df)
math_mean_tokens, math_percent_correct = compute_metrics(math_df)

print("AIME mean generated_think_tokens:", aime_mean_tokens)
print("AIME percent correct:", aime_percent_correct)
print("Math mean generated_think_tokens:", math_mean_tokens)
print("Math percent correct:", math_percent_correct)

AIME mean generated_think_tokens: 2304.292
AIME percent correct: 47.599999999999994
Math mean generated_think_tokens: 680.812
Math percent correct: 74.6

In [57]:
df = pd.read_parquet(Path().resolve() / "regressor_results_eval_L1.parquet")
df_dataset = pd.read_parquet(Path().resolve() /"data" /"processed"/"eval_L1_bert"/ "gsm8k_olympiad_amc.parquet")
df['dataset'] = df_dataset['dataset']
mask_gsm8k = df["dataset"]=="gsm8k"
mask_amc = df["dataset"]=="amc"
mask_olympiad = df["dataset"]=="olympiad"

gsm8k_mean_tokens, gsm8k_percent_correct = compute_metrics(df[mask_gsm8k])
amc_mean_tokens, amc_percent_correct = compute_metrics(df[mask_amc])
olympiad_mean_tokens, olympiad_percent_correct = compute_metrics(df[mask_olympiad])

print("Metrics:")
print(f"  GSM8K     | mean_tokens: {gsm8k_mean_tokens:.2f} | percent_correct: {aime_percent_correct:.2f}")
print(f"  AMC       | mean_tokens: {amc_mean_tokens:.2f} | percent_correct: {amc_percent_correct:.2f}")
print(f"  Olympiad  | mean_tokens: {olympiad_mean_tokens:.2f} | percent_correct: {olympiad_percent_correct:.2f}")

Metrics:
  GSM8K     | mean_tokens: 83.88 | percent_correct: 82.56
  AMC       | mean_tokens: 1169.50 | percent_correct: 62.50
  Olympiad  | mean_tokens: 1794.87 | percent_correct: 39.32

In [58]:
df = pd.read_parquet(Path().resolve() / "regressor_results_eval_bert.parquet")
df_dataset = pd.read_parquet(Path().resolve() /"data" /"processed"/"eval_L1_bert"/ "gsm8k_olympiad_amc.parquet")
df['dataset'] = df_dataset['dataset']
mask_gsm8k = df["dataset"]=="gsm8k"
mask_amc = df["dataset"]=="amc"
mask_olympiad = df["dataset"]=="olympiad"

gsm8k_mean_tokens, gsm8k_percent_correct = compute_metrics(df[mask_gsm8k])
amc_mean_tokens, amc_percent_correct = compute_metrics(df[mask_amc])
olympiad_mean_tokens, olympiad_percent_correct = compute_metrics(df[mask_olympiad])

print("Metrics:")
print(f"  GSM8K     | mean_tokens: {gsm8k_mean_tokens:.2f} | percent_correct: {aime_percent_correct:.2f}")
print(f"  AMC       | mean_tokens: {amc_mean_tokens:.2f} | percent_correct: {amc_percent_correct:.2f}")
print(f"  Olympiad  | mean_tokens: {olympiad_mean_tokens:.2f} | percent_correct: {olympiad_percent_correct:.2f}")

Metrics:
  GSM8K     | mean_tokens: 109.85 | percent_correct: 82.56
  AMC       | mean_tokens: 763.92 | percent_correct: 60.00
  Olympiad  | mean_tokens: 2054.28 | percent_correct: 39.61

In [31]:
df_bert = pd.read_parquet(Path().resolve() / "regressor_results_aime_correct.parquet")
common_ids = set(df_bert["question_id"]).intersection(df["question_id"])
df_filtered = df[df["question_id"].isin(common_ids)]
aime_df, math_df = split_by_question_type(df_filtered)

aime_mean_tokens, aime_percent_correct = compute_metrics(aime_df)
math_mean_tokens, math_percent_correct = compute_metrics(math_df)

print("AIME mean generated_think_tokens:", aime_mean_tokens)
print("AIME percent correct:", aime_percent_correct)
print("Math mean generated_think_tokens:", math_mean_tokens)
print("Math percent correct:", math_percent_correct)

AIME mean generated_think_tokens: 2469.492
AIME percent correct: 52.0
Math mean generated_think_tokens: 690.486
Math percent correct: 74.8

In [4]:
from launch_regressor_jeroen import evaluate_answer, extract_boxed

for i in range(len(df)):
    row = df.iloc[i]
    full_text = row['generated_text']
    gen_val = extract_boxed(full_text)
    if gen_val is None:
        print("=====================================================")
        print(row['prompt'])

/scratch/s3799042/venvs/think-reduction/lib/python3.10/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/scratch/s3799042/venvs/think-reduction/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

=====================================================
<|im_start|>user
Solve for $x$: $2^{2x} = 256^\frac{1}{2}$. Let’s think step by step inside and output the final answer within boxed{}. Think for 100 tokens. <think><|im_end|>
<|im_start|>assistant

=====================================================
<|im_start|>user
Consider the geometric series $4+\frac{12}{a}+\frac{36}{a^2}+\cdots$. If the sum is a perfect square, what is the smallest possible value of $a$ where $a$ is a positive integer? Let’s think step by step inside and output the final answer within boxed{}. Think for 615 tokens. <think><|im_end|>
<|im_start|>assistant

=====================================================
<|im_start|>user
Let $a > 1$ and $x > 1$ satisfy $\log_a(\log_a(\log_a 2) + \log_a 24 - 128) = 128$ and $\log_a(\log_a x) = 256$ . Find the remainder when $x$ is divided by $1000$ . Let’s think step by step inside and output the final answer within boxed{}. Think for 1905 tokens. <think><|im_end|>
<|im_start|>assistant

In [15]:
for i in range(len(df)):
    row = df.iloc[i]
    full_text = row['generated_text']
    gen_val = extract_boxed(full_text)
    if gen_val is None:
        print("=====================================================")
        print(row['generated_text'])
        break

=====================================================
What is the average of the two smallest positive integer solutions to the congruence $$14u \equiv 46 \pmod{100}~?$$ Let’s think step by step inside and output the final answer within boxed{}. Think for 615 tokens. <think>
Okay, solve 14u ≡ 46 mod 100. First, find gcd(14,100)=2. Since 2 divides 46, solutions exist. Divide equation by 2: 7u ≡ 23 mod 50. Find inverse of 7 mod 50. 7*29=203≡3 mod50. 7*?≡1. 7*?≡1. 7*23=161≡11. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*

In [ ]:
import numpy as np
TEST_TARGET_TOKENS = Path().resolve() / "regressor" / "test_target_tokens_L1.npy"
target_tokens = np.load(TEST_TARGET_TOKENS, allow_pickle=True)

In [64]:
df_test_targets = pd.read_parquet(Path().resolve() / "data" / "processed" / "dataset_splitting" /"test.parquet")
g = df_test_targets.groupby("question_id")

result = df_test_targets.loc[
    g["is_correct"].idxmax().where(
        g["is_correct"].any(),
        g.head(1).index
    )
]

result

,question_id,prompt,solution_col,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct,level
0,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, 2^8 is 256. 4^x is (2^2)^x = 2^(2x). So ...","If $2^8=4^x$, what is the value of $x$? Let’s ...",100,53,0.906188,True,Level 5
20,1256,For what values of $x$ is it true that $x^2 - ...,"Re-arranging, $x^2 - 5x - 14 \le 0$. The left-...","Okay, solve the inequality x² -5x -4 ≤ 10.\n\n...",For what values of $x$ is it true that $x^2 - ...,100,103,0.906188,False,Level 5
42,1265,What is the smallest real number $x$ in the do...,A real number $x$ is in the domain of $g$ if a...,"Okay, simplify the expression under the square...",What is the smallest real number $x$ in the do...,615,142,0.906188,True,Level 2
60,1268,Ten treeks weigh as much as three squigs and o...,"Let $t,s,g$ be the weight of one treek, the we...","Let’s denote T, S, G. 10T = 3S + G. 2T + G = S...",Ten treeks weigh as much as three squigs and o...,100,36,0.906188,True,Level 4
82,1284,Consider the geometric sequence $\frac{125}{9}...,The common ratio between consecutive terms is ...,"Okay, first find the common ratio. Divide the ...",Consider the geometric sequence $\frac{125}{9}...,615,237,0.906188,True,Level 1
...,...,...,...,...,...,...,...,...,...,...
14900,aime_924,Alice chooses a set $A$ of positive integers. ...,55,"Okay, the number of sets is 2^k -1 = 2024. So ...",Alice chooses a set $A$ of positive integers. ...,100,44,1.130943,False,aime
14972,aime_930,Let $\omega\neq 1$ be a 13th root of unity. Fi...,321,"Okay, so I need to find the remainder when the...",Let $\omega\neq 1$ be a 13th root of unity. Fi...,3194,2437,1.130943,True,aime
14940,aime_928,Find the number of triples of nonnegative inte...,601,"Okay, the equation simplifies to ab(a + b) + b...",Find the number of triples of nonnegative inte...,100,51,1.130943,False,aime
10604,aime_96,"A triangle has vertices $P_{}^{}=(-8,5)$ , $Q_...",89,"Okay, I need to find the equation of the angle...","A triangle has vertices $P_{}^{}=(-8,5)$ , $Q_...",1131,553,1.130943,True,aime
10622,aime_97,A fair coin is to be tossed $10_{}^{}$ times. ...,73,"Okay, so I need to find the probability that i...",A fair coin is to be tossed $10_{}^{}$ times. ...,615,145,1.130943,True,aime

In [80]:
df_test_predictions_L1 = pd.read_parquet(Path().resolve() / "regressor_results_test_L1.parquet")
df_test_predictions_L1

,question_id,prompt,solution,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct
0,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, 2^8 is 256. 4^x is (2^2)^x = 2^(2x). So ...","If $2^8=4^x$, what is the value of $x$? Let’s ...",100,56,0.565635,False
1,1256,For what values of $x$ is it true that $x^2 - ...,"Re-arranging, $x^2 - 5x - 14 \le 0$. The left-...","Okay, solve the inequality x² -5x -4 ≤ 10.\n\n...",For what values of $x$ is it true that $x^2 - ...,100,103,0.565635,False
2,1265,What is the smallest real number $x$ in the do...,A real number $x$ is in the domain of $g$ if a...,"Okay, simplify the expression under the square...",What is the smallest real number $x$ in the do...,615,160,0.565635,False
3,1268,Ten treeks weigh as much as three squigs and o...,"Let $t,s,g$ be the weight of one treek, the we...","Okay, let me solve this. Let T, S, G be weight...",Ten treeks weigh as much as three squigs and o...,357,114,0.565635,False
4,1284,Consider the geometric sequence $\frac{125}{9}...,The common ratio between consecutive terms is ...,"Okay, find the common ratio by dividing the se...",Consider the geometric sequence $\frac{125}{9}...,357,95,0.565635,False
...,...,...,...,...,...,...,...,...,...
745,aime_928,Find the number of triples of nonnegative inte...,601,"Okay, so I need to find the number of triples ...",Find the number of triples of nonnegative inte...,4484,3552,0.565635,False
746,aime_930,Let $\omega\neq 1$ be a 13th root of unity. Fi...,321,"Okay, so I need to find the remainder when the...",Let $\omega\neq 1$ be a 13th root of unity. Fi...,5000,3623,0.565635,True
747,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,5000,3932,0.565635,False
748,aime_96,"A triangle has vertices $P_{}^{}=(-8,5)$ , $Q_...",89,"Okay, so I need to find the equation of the an...","A triangle has vertices $P_{}^{}=(-8,5)$ , $Q_...",4484,2575,0.565635,True
749,aime_97,A fair coin is to be tossed $10_{}^{}$ times. ...,73,"Okay, so I need to find the probability that w...",A fair coin is to be tossed $10_{}^{}$ times. ...,5000,3499,0.565635,True

In [81]:
result = result.reset_index()

percentage = (
    (result["target_think_tokens"] == df_test_predictions_L1["target_think_tokens"])
    .mean() * 100
)

percentage

np.float64(20.933333333333334)

In [76]:
Path().resolve() / "regressor" / "test_target_tokens_bert_06.npy"

PosixPath('/home/s3799042/projects/llm-think-too-much/regressor/test_target_tokens_bert_06.npy')

In [78]:
df_test_predictions_bert = pd.read_parquet(Path().resolve() / "regressor_results_test_bert.parquet")
df_test_predictions_bert

,question_id,prompt,solution,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct
0,1254,"If $2^8=4^x$, what is the value of $x$? Let’s ...",Rewrite $4$ as $2^2$ to find $4^x=2^{2x}$. Si...,"Okay, 2^8 is 256. 4^x is (2^2)^x = 2^(2x). So ...","If $2^8=4^x$, what is the value of $x$? Let’s ...",100,55,0.58372,False
1,1256,For what values of $x$ is it true that $x^2 - ...,"Re-arranging, $x^2 - 5x - 14 \le 0$. The left-...","Okay, solve the inequality: x² -5x -4 ≤ 10.\n\...",For what values of $x$ is it true that $x^2 - ...,100,104,0.58372,False
2,1265,What is the smallest real number $x$ in the do...,A real number $x$ is in the domain of $g$ if a...,"Okay, simplify the expression under the square...",What is the smallest real number $x$ in the do...,357,84,0.58372,False
3,1268,Ten treeks weigh as much as three squigs and o...,"Let $t,s,g$ be the weight of one treek, the we...","Okay, let me solve this. Let T, S, G be weight...",Ten treeks weigh as much as three squigs and o...,357,109,0.58372,False
4,1284,Consider the geometric sequence $\frac{125}{9}...,The common ratio between consecutive terms is ...,"Okay, first find the common ratio. Divide seco...",Consider the geometric sequence $\frac{125}{9}...,357,108,0.58372,False
...,...,...,...,...,...,...,...,...,...
745,aime_928,Find the number of triples of nonnegative inte...,601,"Okay, so I need to find the number of triples ...",Find the number of triples of nonnegative inte...,2678,1991,0.58372,False
746,aime_930,Let $\omega\neq 1$ be a 13th root of unity. Fi...,321,"Okay, so I need to find the product of (2 - 2ω...",Let $\omega\neq 1$ be a 13th root of unity. Fi...,1647,1137,0.58372,False
747,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,3968,2256,0.58372,False
748,aime_96,"A triangle has vertices $P_{}^{}=(-8,5)$ , $Q_...",89,"Okay, so I need to find the equation of the an...","A triangle has vertices $P_{}^{}=(-8,5)$ , $Q_...",1647,1003,0.58372,True
749,aime_97,A fair coin is to be tossed $10_{}^{}$ times. ...,73,"Okay, so I need to find the probability that w...",A fair coin is to be tossed $10_{}^{}$ times. ...,4484,2808,0.58372,True

In [101]:
merged = result.merge(df_test_predictions_bert, on="question_id", suffixes=("_r", "_o"))

percentage = (
    (merged["target_think_tokens_r"] == merged["target_think_tokens_o"])
    .mean() * 100
)
percentage

np.float64(17.2)

In [99]:
merged = result.merge(df_test_predictions_bert, on="question_id", suffixes=("_r", "_o"))
subset = merged[merged["is_correct_r"]]

percentage = (
    (subset["target_think_tokens_r"] == subset["target_think_tokens_o"])
    .mean() * 100
)
percentage

np.float64(18.61861861861862)

In [100]:
distance = (subset["target_think_tokens_r"] - subset["target_think_tokens_o"]).mean()
distance

np.float64(-1011.3813813813814)

In [102]:
merged = result.merge(df_test_predictions_L1, on="question_id", suffixes=("_r", "_o"))
subset = merged[merged["is_correct_r"]]

percentage = (
    (subset["target_think_tokens_r"] == subset["target_think_tokens_o"])
    .mean() * 100
)
percentage

np.float64(22.972972972972975)

In [103]:
distance = (subset["target_think_tokens_r"] - subset["target_think_tokens_o"]).mean()
distance

np.float64(-1028.054054054054)