In [2]:
import pandas as pd
from pathlib import Path


def split_by_question_type(df):
    aime_mask = df["question_id"].str.contains("aime", case=False, na=False)
    #aime_mask = df["question_id"] >= 500
    return df[aime_mask], df[~aime_mask]


def compute_metrics(df):
    mean_tokens = df["generated_think_tokens"].mean()
    percent_correct = df["is_correct"].mean() * 100
    return mean_tokens, percent_correct

In [32]:
df = pd.read_parquet(Path().resolve() / "regressor_results_aime_correct.parquet")
aime_df, math_df = split_by_question_type(df)

aime_mean_tokens, aime_percent_correct = compute_metrics(aime_df)
math_mean_tokens, math_percent_correct = compute_metrics(math_df)

print("AIME mean generated_think_tokens:", aime_mean_tokens)
print("AIME percent correct:", aime_percent_correct)
print("Math mean generated_think_tokens:", math_mean_tokens)
print("Math percent correct:", math_percent_correct)

AIME mean generated_think_tokens: 2469.492
AIME percent correct: 52.0
Math mean generated_think_tokens: 690.486
Math percent correct: 74.8

In [31]:
df_bert = pd.read_parquet(Path().resolve() / "regressor_results_aime_correct.parquet")
common_ids = set(df_bert["question_id"]).intersection(df["question_id"])
df_filtered = df[df["question_id"].isin(common_ids)]
aime_df, math_df = split_by_question_type(df_filtered)

aime_mean_tokens, aime_percent_correct = compute_metrics(aime_df)
math_mean_tokens, math_percent_correct = compute_metrics(math_df)

print("AIME mean generated_think_tokens:", aime_mean_tokens)
print("AIME percent correct:", aime_percent_correct)
print("Math mean generated_think_tokens:", math_mean_tokens)
print("Math percent correct:", math_percent_correct)

AIME mean generated_think_tokens: 2469.492
AIME percent correct: 52.0
Math mean generated_think_tokens: 690.486
Math percent correct: 74.8

In [4]:
from launch_regressor_jeroen import evaluate_answer, extract_boxed

for i in range(len(df)):
    row = df.iloc[i]
    full_text = row['generated_text']
    gen_val = extract_boxed(full_text)
    if gen_val is None:
        print("=====================================================")
        print(row['prompt'])

/scratch/s3799042/venvs/think-reduction/lib/python3.10/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/scratch/s3799042/venvs/think-reduction/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

=====================================================
<|im_start|>user
Solve for $x$: $2^{2x} = 256^\frac{1}{2}$. Let’s think step by step inside and output the final answer within boxed{}. Think for 100 tokens. <think><|im_end|>
<|im_start|>assistant

=====================================================
<|im_start|>user
Consider the geometric series $4+\frac{12}{a}+\frac{36}{a^2}+\cdots$. If the sum is a perfect square, what is the smallest possible value of $a$ where $a$ is a positive integer? Let’s think step by step inside and output the final answer within boxed{}. Think for 615 tokens. <think><|im_end|>
<|im_start|>assistant

=====================================================
<|im_start|>user
Let $a > 1$ and $x > 1$ satisfy $\log_a(\log_a(\log_a 2) + \log_a 24 - 128) = 128$ and $\log_a(\log_a x) = 256$ . Find the remainder when $x$ is divided by $1000$ . Let’s think step by step inside and output the final answer within boxed{}. Think for 1905 tokens. <think><|im_end|>
<|im_start|>assistant

In [15]:
for i in range(len(df)):
    row = df.iloc[i]
    full_text = row['generated_text']
    gen_val = extract_boxed(full_text)
    if gen_val is None:
        print("=====================================================")
        print(row['generated_text'])
        break

=====================================================
What is the average of the two smallest positive integer solutions to the congruence $$14u \equiv 46 \pmod{100}~?$$ Let’s think step by step inside and output the final answer within boxed{}. Think for 615 tokens. <think>
Okay, solve 14u ≡ 46 mod 100. First, find gcd(14,100)=2. Since 2 divides 46, solutions exist. Divide equation by 2: 7u ≡ 23 mod 50. Find inverse of 7 mod 50. 7*29=203≡3 mod50. 7*?≡1. 7*?≡1. 7*23=161≡11. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*?≡1. 7*

In [16]:
import numpy as np
TEST_TARGET_TOKENS = Path().resolve() / "regressor" / "test_target_tokens_L1.npy"
target_tokens = np.load(TEST_TARGET_TOKENS, allow_pickle=True)

In [17]:
target_tokens

array({'ids': 0            1254
20           1256
40           1265
60           1268
80           1284
           ...
14900    aime_924
14920    aime_927
14940    aime_928
14960    aime_930
14980    aime_931
Name: question_id, Length: 750, dtype: object, 'target': array([ 100,  100,  357,  357,  100, 1131,  615,  100,  357,  100,  615,
        615,  100,  100,  357,  100,  357,  615,  100,  100,  357,  357,
        100,  615,  100,  615,  100,  100,  357, 4484,  615,  100,  100,
        100,  615, 1389,  100,  357,  100,  100,  100,  100,  357,  100,
        357,  357,  873,  357,  357,  615,  100,  357,  615,  615,  100,
        100,  100,  615,  100,  357,  357, 1131,  357,  615,  100, 1389,
        357,  357,  100,  357,  357,  100, 1389,  100,  100,  100,  100,
        100, 1389,  100,  615,  100,  357,  357,  615,  615,  100,  873,
       1131,  357,  100,  100,  100,  100,  100,  357,  357,  100,  357,
        100,  357,  615,  100,  100,  615,  357,  100, 3968,  100,  100,
        615,  615,  357,  100,  873,  357,  100,  357, 1389,  615,  357,
        357,  357,  357,  615, 4742,  357,  357,  100,  357,  100,  357,
        615,  357, 4742, 4484, 1131,  100, 2163,  873, 2163, 1647,  100,
        357, 1647,  100,  615,  100, 1389,  357,  100, 1647,  873,  100,
       5000, 1131,  100, 1131,  357, 1131, 2163,  615,  100,  615,  100,
        615, 4742,  357, 1389,  615, 3968, 1131,  100,  100,  615,  100,
        100, 3194,  100, 4484,  100,  357,  100,  873, 1131, 4742,  357,
        615, 5000, 4484, 3968, 4742,  100,  357,  100, 4484, 4484,  357,
       5000, 4742, 1131, 4742,  100, 1389, 1389,  615, 1131, 3452, 4742,
        357,  615,  873,  873, 1389,  100, 1647, 4484,  615,  615,  615,
        615, 1647, 4484, 3710,  357,  100, 2678,  873, 1647, 4484, 4484,
       1389, 1389,  873, 1389, 1647, 2678, 1905, 1389,  100,  873, 3968,
       4484, 1131, 1131,  357, 1389,  100,  873, 1389,  873, 1647, 1131,
        357, 4484,  615, 1131, 2421,  615,  615, 1389, 1389, 4484, 4484,
        615,  615, 3968,  873, 1131,  615, 4742,  357, 3452, 1131,  873,
        357,  615, 1389,  357, 4484, 3452,  615, 1389,  357, 4742,  873,
        357, 1389,  615,  615,  100, 3968, 3968, 1389,  873, 1647, 3968,
       1131,  615, 1389,  357, 1389, 1131, 1131,  615,  357, 3194,  357,
       1131,  615,  100,  615,  615,  615,  100,  615,  357,  615,  357,
        615, 1131,  100,  100,  100,  615, 3968,  100, 1131,  615,  100,
        100,  615,  100,  100,  615,  615, 5000,  100,  357,  100,  615,
        615,  357,  357,  357, 1389,  100,  100,  100,  100,  357,  615,
        873,  357, 3194,  615,  100,  357,  100,  615,  100,  357, 4484,
       1131,  615,  100,  357,  615, 2936,  615,  100,  100,  100,  100,
        100,  100,  100,  100, 1647,  100,  100,  100,  615,  100,  100,
        100,  615,  100,  357,  873,  357,  615,  100,  100,  615, 5000,
        100,  357,  357, 5000,  100,  357,  100,  100,  100,  357,  615,
        357,  100,  357, 1389,  100,  100,  100,  100,  100, 1647,  357,
        357,  615,  100,  100,  100,  100,  357,  357, 4226,  100,  615,
        615,  100,  100, 4226,  615, 1647,  100, 4226, 1389, 1389,  357,
        100,  100,  100,  100, 1647, 4226,  100, 2936, 1389, 1389,  615,
        615, 4484, 4484, 1131, 2936,  100, 1389,  615,  357, 1389, 1131,
       3710,  357, 1131,  873, 1389,  357,  357,  873,  100, 4484,  357,
       4742,  615, 4484,  357, 1647,  100,  615,  615,  357,  615, 1131,
       4484,  615, 4484,  357, 1131,  873, 1905,  615,  873,  873, 1647,
       1131,  615, 1131, 3452, 1389, 3194, 4484, 3452, 4484, 4742, 3452,
       3452,  357, 1389, 4742,  873, 3452, 3452, 4226, 5000,  357, 2163,
       2678, 4742, 4742, 1131, 5000, 3452, 4484, 2163, 3452, 3968,  615,
       4742, 3452, 3452, 1905, 3452, 3968, 3452, 4484, 5000, 2678, 4742,
       2678, 3710, 4484, 4742, 3968, 3452, 3452, 1905, 4484, 4484, 3968,
       3452, 4742, 3968, 1131, 3710, 3710, 2678, 4742, 3452, 3968, 3452,
       4742, 3452, 3710, 3194, 3194, 3968, 3968, 3194, 3968, 4742, 3452,
       3452, 3452, 2678, 1389, 2678, 3452, 2678, 3968, 3194, 3452, 5000,
        615, 2163, 4742, 3968, 3194, 4742, 4742, 3452, 4484, 2163, 3452,
       2678, 4742, 3452, 3452, 4742, 4742, 3968, 4742, 3968, 3968, 4484,
       3968, 4484, 5000, 5000, 3968, 4484, 3968, 2678, 3968, 3452, 3968,
       3452, 3968,  873, 4742, 3968, 4484, 3452, 4742, 3452, 4742, 3452,
       1647, 3710, 2678, 3452, 3968, 3452, 3968, 4742, 3968, 3452, 3452,
       3968, 3452, 3452, 4742, 2678, 3452, 3452, 3452, 3452, 3194, 3194,
       3968, 2163, 1905, 3452, 3452, 3452, 1905, 3452, 1905, 1389, 3968,
       3452, 3710, 3452, 3194, 3452, 2678, 3452, 3452, 3710, 3452, 3452,
       1905, 1905, 3452, 3710, 3452, 4742, 3452, 3452, 3968, 3452, 2678,
       1905, 3452, 2678, 1647, 1905, 3710, 3452, 3452, 3452, 3968, 4742,
       3968, 5000, 3452, 3452, 4742, 1905, 3968, 3452, 3452, 3968, 3194,
       5000, 2678, 4742, 3452, 3452, 4742, 3452, 4484, 4742, 3968, 3452,
       3968, 3968, 3452, 3968, 2678, 1905, 4742, 3968, 3968, 3452, 5000,
       3452, 3968, 3452, 3968, 2678, 3452, 3452, 3452, 4484, 4742, 3968,
       3452, 3452, 4742, 3968, 2678, 2678, 3968, 4484, 3452, 3452, 3968,
       4484, 3452])}, dtype=object)

In [3]:
df_train = pd.read_parquet(Path().resolve() / "data" / "old" / "dataset_splitting" / "train.parquet")

In [15]:
aime_mask = df_train["question_id"].str.contains("aime", case=False, na=False)
df_aime = df_train[aime_mask]
df_math = df_train[~aime_mask]

In [9]:
from launch_regressor_jeroen import evaluate_answer, extract_boxed, is_equiv

answer_correctness = []
for i in range(len(df_aime)):
    row = df_aime.iloc[i]
    full_text = row['generated_text']
    gen_val = extract_boxed(full_text)
    exp_val = row['solution_col']
    if exp_val is None:
        print("Expected value is none")

    
    if gen_val is None:
        print("Generated value is none")

    answer_correctness.append(is_equiv(gen_val, exp_val))

Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none

In [13]:
df_aime_corrected = df_aime
df_aime_corrected['is_correct'] =  answer_correctness
df_aime_corrected[:10]

/tmp/ipykernel_2828115/3181818088.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_aime_corrected['is_correct'] =  answer_correctness

,question_id,prompt,solution_col,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct,level
240000,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, let me try. Use change of base formula a...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",100,28,1.130943,True,aime
240001,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, using change of base formula, express al...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",357,86,1.130943,True,aime
240002,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I have log base x of w is 24, log bas...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",615,237,1.130943,True,aime
240003,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w. Given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",873,363,1.130943,True,aime
240004,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w, given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",1131,599,1.130943,False,aime
240005,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w, given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",1389,712,1.130943,True,aime
240006,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w, given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",1647,965,1.130943,True,aime
240007,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w, given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",1905,1024,1.130943,True,aime
240008,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w, given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",2163,1123,1.130943,True,aime
240009,aime_0,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,"Okay, so I need to find log base z of w, given...","Let $x$ , $y$ and $z$ all exceed $1$ and let $...",2421,1325,1.130943,True,aime

In [16]:
df_train_corrected = pd.concat([df_math, df_aime_corrected], ignore_index = True)
df_train_corrected

,question_id,prompt,solution_col,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct,level
0,0,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...","For the piecewise function to be continuous, t...","Okay, set limits at x=2 and x=-2. Solve for a ...","Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",100,22,0.928551,False,Level 5
1,0,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...","For the piecewise function to be continuous, t...","Okay, for continuity at x=2 and x=-2, set limi...","Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",357,90,0.928551,False,Level 5
2,0,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...","For the piecewise function to be continuous, t...","Okay, to ensure continuity, the function's lef...","Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",615,182,0.928551,True,Level 5
3,0,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...","For the piecewise function to be continuous, t...","Okay, so I need to find a and b to make the fu...","Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",873,283,0.928551,True,Level 5
4,0,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...","For the piecewise function to be continuous, t...","Okay, so I need to find a and b such that the ...","Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",1131,460,0.928551,True,Level 5
...,...,...,...,...,...,...,...,...,...,...
253655,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,3968,2609,1.130943,False,aime
253656,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,4226,3309,1.130943,False,aime
253657,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,4484,2874,1.130943,False,aime
253658,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,4742,3612,1.130943,False,aime
253659,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,5000,3824,1.130943,False,aime

In [17]:
df_train_corrected.to_parquet(Path().resolve() / "data" / "processed" / "dataset_splitting" / "train.parquet")

In [ ]:
path_train_targets_hidden = Path().resolve() / "data" / "processed" / "train" / "train_targets_hidden.parquet"
df_train_targets_hidden = pd.read_parquet(path_train_targets_hidden)

,question_id,prompt,solution_col,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct,level,hidden
10000,500,A $100$-gon $P_1$ is drawn in the Cartesian pl...,Let the $x$-coordinates of the vertices of $P_...,"Okay, the sum of x-coordinates of P3 is 2009 d...",A $100$-gon $P_1$ is drawn in the Cartesian pl...,100,44,0.928551,False,Level 5,"[-1.406, 0.1992, -0.5703, 0.0437, -2.078, 0.50..."
10001,500,A $100$-gon $P_1$ is drawn in the Cartesian pl...,Let the $x$-coordinates of the vertices of $P_...,"Okay, the sum of x-coordinates of P3 is half o...",A $100$-gon $P_1$ is drawn in the Cartesian pl...,357,63,0.928551,False,Level 5,"[-1.406, 0.1992, -0.5703, 0.0437, -2.078, 0.50..."
10002,500,A $100$-gon $P_1$ is drawn in the Cartesian pl...,Let the $x$-coordinates of the vertices of $P_...,"Okay, the key is understanding how the midpoin...",A $100$-gon $P_1$ is drawn in the Cartesian pl...,615,176,0.928551,False,Level 5,"[-1.406, 0.1992, -0.5703, 0.0437, -2.078, 0.50..."
10003,500,A $100$-gon $P_1$ is drawn in the Cartesian pl...,Let the $x$-coordinates of the vertices of $P_...,"Okay, the sum of x-coordinates of P1 is 2009. ...",A $100$-gon $P_1$ is drawn in the Cartesian pl...,873,241,0.928551,False,Level 5,"[-1.406, 0.1992, -0.5703, 0.0437, -2.078, 0.50..."
10004,500,A $100$-gon $P_1$ is drawn in the Cartesian pl...,Let the $x$-coordinates of the vertices of $P_...,"Okay, so there's this 100-gon P1 with the sum ...",A $100$-gon $P_1$ is drawn in the Cartesian pl...,1131,490,0.928551,True,Level 5,"[-1.406, 0.1992, -0.5703, 0.0437, -2.078, 0.50..."
...,...,...,...,...,...,...,...,...,...,...,...
253655,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,3968,2609,1.130943,False,aime,"[-1.125, 0.2207, -1.055, 0.2109, -1.992, 2.5, ..."
253656,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,4226,3309,1.130943,False,aime,"[-1.125, 0.2207, -1.055, 0.2109, -1.992, 2.5, ..."
253657,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,4484,2874,1.130943,False,aime,"[-1.125, 0.2207, -1.055, 0.2109, -1.992, 2.5, ..."
253658,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,4742,3612,1.130943,False,aime,"[-1.125, 0.2207, -1.055, 0.2109, -1.992, 2.5, ..."
253659,aime_932,Find the number of rectangles that can be form...,315,"Okay, so I need to figure out how many rectang...",Find the number of rectangles that can be form...,5000,3824,1.130943,False,aime,"[-1.125, 0.2207, -1.055, 0.2109, -1.992, 2.5, ..."

In [ ]:
df_train_targets_hidden_aime_mask = df_train_targets_hidden["question_id"].str.contains("aime", case=False, na=False)
df_aime_hidden = df_train_targets_hidden[df_train_targets_hidden_aime_mask]
df_math_hidden = df_train_targets_hidden[~df_train_targets_hidden_aime_mask]

In [40]:
def reevaluate_correctness_aime(df_aime):
    answer_correctness = []
    for i in range(len(df_aime)):
        row = df_aime.iloc[i]
        full_text = row['generated_text']
        gen_val = extract_boxed(full_text)
        exp_val = row['solution_col']
        if exp_val is None:
            print("Expected value is none")

        
        if gen_val is None:
            print("Generated value is none")

        answer_correctness.append(is_equiv(gen_val, exp_val))

    df_aime['is_correct'] = answer_correctness
    return df_aime

In [23]:
answer_correctness = []
for i in range(len(df_aime_hidden)):
    row = df_aime_hidden.iloc[i]
    full_text = row['generated_text']
    gen_val = extract_boxed(full_text)
    exp_val = row['solution_col']
    if exp_val is None:
        print("Expected value is none")

    
    if gen_val is None:
        print("Generated value is none")

    answer_correctness.append(is_equiv(gen_val, exp_val))


df_aime_hidden_corrected = df_aime_hidden
df_aime_hidden_corrected['is_correct'] = answer_correctness

Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none

/tmp/ipykernel_2828115/3830165262.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_aime_hidden_corrected['is_correct'] = answer_correctness

In [ ]:
df_train_hidden_corrected = pd.concat([df_math_hidden, df_aime_hidden_corrected], ignore_index = True)
df_train_hidden_corrected.to_parquet(Path().resolve() / "data" / "processed" / "dataset_splitting" / "train_targets_hidden.parquet")

In [44]:
df_test = pd.read_parquet(Path().resolve() / "data" / "old" / "dataset_splitting" / "test.parquet")
df_test_aime_mask = df_test["question_id"].str.contains("aime", case=False, na=False)
df_test_aime = df_test[df_test_aime_mask]
df_test_math = df_test[~df_test_aime_mask]

In [45]:
df_test_aime_corrected = reevaluate_correctness_aime(df_test_aime)
df_test_corrected = pd.concat([df_test_math, df_test_aime], ignore_index=True)
df_test_corrected.to_parquet(Path().resolve() / "data" / "processed" / "dataset_splitting" / "test.parquet")

Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none

/tmp/ipykernel_2828115/749550284.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_aime['is_correct'] = answer_correctness

In [47]:
path_test_targets_hidden = Path().resolve() / "data" / "processed" / "train" / "test_targets_hidden.parquet"
df_test_targets_hidden = pd.read_parquet(path_test_targets_hidden)

In [48]:
df_test_hidden_aime_mask = df_test_targets_hidden["question_id"].str.contains("aime", case=False, na=False)
df_test_hidden_aime = df_test_targets_hidden[df_test_hidden_aime_mask]
df_test_hidden_math = df_test_targets_hidden[~df_test_hidden_aime_mask]

df_test_hidden_aime

,question_id,prompt,solution_col,generated_think_text,generated_text,target_think_tokens,generated_think_tokens,latency_sec,is_correct,level,hidden
10000,aime_2,What is the product of the real roots of the e...,20,"Okay, let me try. Let u = x² + 18x + 30. Then ...",What is the product of the real roots of the e...,100,67,1.130943,False,aime,"[-1.0, 0.4277, -0.1807, 0.1719, -1.742, 1.75, ..."
10001,aime_2,What is the product of the real roots of the e...,20,"Okay, let me try. Let’s set y = x² + 18x + 30....",What is the product of the real roots of the e...,357,114,1.130943,False,aime,"[-1.0, 0.4277, -0.1807, 0.1719, -1.742, 1.75, ..."
10002,aime_2,What is the product of the real roots of the e...,20,"Okay, let me try. Let’s set y = x² + 18x + 30....",What is the product of the real roots of the e...,615,255,1.130943,False,aime,"[-1.0, 0.4277, -0.1807, 0.1719, -1.742, 1.75, ..."
10003,aime_2,What is the product of the real roots of the e...,20,"Okay, let me try. The equation is x² + 18x + 3...",What is the product of the real roots of the e...,873,356,1.130943,False,aime,"[-1.0, 0.4277, -0.1807, 0.1719, -1.742, 1.75, ..."
10004,aime_2,What is the product of the real roots of the e...,20,"Okay, let me try to solve this equation. The e...",What is the product of the real roots of the e...,1131,538,1.130943,False,aime,"[-1.0, 0.4277, -0.1807, 0.1719, -1.742, 1.75, ..."
...,...,...,...,...,...,...,...,...,...,...,...
14995,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (a...",Let $b \geq 2$ be an integer. Call a positive ...,3968,2658,1.130943,False,aime,"[-1.18, -0.4004, -0.8984, 0.1445, -1.609, 1.33..."
14996,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,4226,2607,1.130943,False,aime,"[-1.18, -0.4004, -0.8984, 0.1445, -1.609, 1.33..."
14997,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,4484,3041,1.130943,False,aime,"[-1.18, -0.4004, -0.8984, 0.1445, -1.609, 1.33..."
14998,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,4742,2568,1.130943,False,aime,"[-1.18, -0.4004, -0.8984, 0.1445, -1.609, 1.33..."
14999,aime_931,Let $b \geq 2$ be an integer. Call a positive ...,211,"Okay, so I need to find the smallest base b (w...",Let $b \geq 2$ be an integer. Call a positive ...,5000,2827,1.130943,False,aime,"[-1.18, -0.4004, -0.8984, 0.1445, -1.609, 1.33..."

In [49]:
df_test_hidden_aime_corrected = reevaluate_correctness_aime(df_test_hidden_aime)
df_test_hidden_corrected = pd.concat([df_test_hidden_math, df_test_hidden_aime_corrected], ignore_index=True)
df_test_hidden_corrected.to_parquet(Path().resolve() / "data" / "processed" / "dataset_splitting" / "test_targets_hidden.parquet")

Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none
Generated value is none

/tmp/ipykernel_2828115/749550284.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_aime['is_correct'] = answer_correctness